#!/usr/bin/env bash
# Build and test only HeadroomCore, on any platform (used by the Linux CI job).
#
# `swift test` always builds every target in the package, and the app, CLI and
# probes need AppKit / Darwin. So this copies HeadroomCore and its tests into a
# throwaway package that contains nothing else, then builds and tests that.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="${HEADROOM_CORE_PKG:-$ROOT/.build/core-only}"

say() { printf '==> %s\n' "$*"; }

command -v swift >/dev/null 2>&1 || { echo "error: swift not found" >&2; exit 1; }
[ -d "$ROOT/Sources/HeadroomCore" ] || { echo "error: Sources/HeadroomCore missing" >&2; exit 1; }

rm -rf "$WORK/Sources" "$WORK/Tests"
mkdir -p "$WORK/Sources" "$WORK/Tests"
cp -R "$ROOT/Sources/HeadroomCore" "$WORK/Sources/HeadroomCore"

HAS_TESTS=0
if [ -d "$ROOT/Tests/HeadroomCoreTests" ]; then
    cp -R "$ROOT/Tests/HeadroomCoreTests" "$WORK/Tests/HeadroomCoreTests"
    HAS_TESTS=1
fi

{
    echo '// swift-tools-version:5.9'
    echo '// Generated by scripts/test-core-linux.sh. Do not edit.'
    echo 'import PackageDescription'
    echo 'let package = Package('
    echo '    name: "HeadroomCoreOnly",'
    echo '    targets: ['
    echo '        .target(name: "HeadroomCore"),'
    if [ "$HAS_TESTS" = "1" ]; then
        echo '        .testTarget(name: "HeadroomCoreTests", dependencies: ["HeadroomCore"]),'
    fi
    echo '    ]'
    echo ')'
} > "$WORK/Package.swift"

cd "$WORK"
say "swift build --target HeadroomCore ($(swift --version 2>&1 | head -1))"
swift build --target HeadroomCore
if [ "$HAS_TESTS" = "1" ]; then
    say "swift test (HeadroomCoreTests)"
    swift test
else
    say "No Tests/HeadroomCoreTests; skipping tests"
fi
